Knightvmk patch 3
knightvmk/mp2-lab1-set pull request #2
Opened 2016-09-28 19:44 UTC by knightvmk

Some Fixes
5 errors

2016-09-28 19:50 UTC, knightvmk commented on src/tset.cpp
> -// ННГУ, ВМК, Курс "Методы программирования-2", С++, ООП
Совместная проверка работоспособности
Удалено из проекта

2016-09-29 19:52 UTC, alvls commented on src/tbitfield.cpp
> +	else printf("\nMEM_ALLOC_FAIL\n");
Не должно быть вывода на экран в методах класса.

2016-09-29 19:52 UTC, alvls commented on src/tbitfield.cpp
> +	else printf("\nMEM_ALLOC_FAIL\nFAIL_OBJECT_COPY\n");
см. выше

2016-09-29 19:53 UTC, alvls commented on src/tbitfield.cpp
> +    //delete[] pMem; //необходимо бы сделать очистку, но тест не пройдется
Что за очистку вы тут хотите делать?

2016-09-29 19:54 UTC, alvls commented on src/tbitfield.cpp
> +	if ((n<0) || (n>BitLen))
Это внутренний метод класса. Здесь проверки и исключения не нужны.

2016-09-29 19:54 UTC, alvls commented on src/tbitfield.cpp
> +	if ((n<0) || (n>BitLen))
см. выше

2016-09-29 19:55 UTC, alvls commented on src/tbitfield.cpp
> +	if ((n<0) || (n>BitLen))
Неверное условие

2016-09-29 19:55 UTC, alvls commented on src/tbitfield.cpp
> +	if ((n<0) || (n>BitLen))
Неверное условие

2016-09-29 19:56 UTC, alvls commented on src/tbitfield.cpp
> +	unsigned int k=0;
Реализуйте != через ==

2016-09-29 19:58 UTC, alvls commented on src/tbitfield.cpp
> +		if (GetBit(i) == 0)
Здесь ошибка. GetBit работает с битами, а граница у цикла - MemLen в элементах типа TElem

2016-09-29 20:00 UTC, alvls commented on src/tset.cpp
> +	if (MaxPower != s.MaxPower) return 0;
лишняя проверка

2016-09-29 20:00 UTC, alvls commented on src/tset.cpp
> +	if (MaxPower == s.MaxPower) return 1;
лишняя проверка

2016-09-29 20:01 UTC, alvls commented on src/tset.cpp
> +	if (Elem<0 || Elem>MaxPower)
плохая реализация. нужно через метод из TBitField сделать.

2016-09-29 20:01 UTC, alvls commented on src/tset.cpp
> +	if (Elem<0 || Elem>MaxPower)
см. выше

2016-09-29 20:03 UTC, alvls requested changes
Исправляйте замечания

2016-09-30 14:07 UTC, knightvmk commented on src/tbitfield.cpp
> +    //delete[] pMem; //необходимо бы сделать очистку, но тест не пройдется
Если есть попытка копировать неравные уже созданные объекты, то необходимо у неравного очистить и заново выделить нужного размера, не так ли? Или я ошибаюсь?

2016-09-30 14:13 UTC, alvls commented on src/tbitfield.cpp
> +    //delete[] pMem; //необходимо бы сделать очистку, но тест не пройдется
Ошибаетесь. Это в операторе = так. А в конструкторе копирования - нет. И я объяснял на паре, почему...

2016-09-30 14:17 UTC, knightvmk commented on src/tbitfield.cpp
> +		if (GetBit(i) == 0)
Спасибо, я голову ломал! Прошёл из-за этого 4 теста!!!

2016-09-30 14:24 UTC, knightvmk commented on src/tbitfield.cpp
> +    //delete[] pMem; //необходимо бы сделать очистку, но тест не пройдется
Разобрался, Но не могу понять пока что почему. Забыл.

2016-09-30 14:25 UTC, knightvmk commented on src/tbitfield.cpp
> +	unsigned int k=0;
Потому что быстрее, если условие истинно?

2016-09-30 14:27 UTC, knightvmk commented on src/tbitfield.cpp
> +	unsigned int k=0;
Или реализовать уже существующим методом выше?

2016-09-30 14:30 UTC, alvls commented on src/tbitfield.cpp
> +	unsigned int k=0;
Да, через метод ==

2016-09-30 14:36 UTC, knightvmk commented on src/tbitfield.cpp
> +	unsigned int k=0;
Готово.

2016-09-30 16:40 UTC, closed without merging